version: '3.5'
networks:
  hubzilla:
  public:
    external: true
volumes:
  voldb:
  volweb:
configs:
  nginx:
    file: nginx.conf
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: hubzilla
      POSTGRES_USER: hubzilla
      POSTGRES_DB: hub
    volumes:
      - voldb:/var/lib/postgresql/data
    networks:
    - hubzilla
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    volumes:
      - volweb:/var/www/html
    networks:
      - hubzilla
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.hubzilla.rule=Host(`domain.com`)
        - traefik.http.routers.hubzilla.tls=true
        - traefik.http.routers.hubzilla.tls.certresolver=le
        - traefik.http.routers.hubzilla.entrypoints=websecure
        - traefik.http.services.hubzilla.loadbalancer.server.port=80
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.routers.redirect.rule=Host(`domain.com`)
        - traefik.http.routers.redirect.middlewares=redirect-to-https
        - traefik.http.routers.redirect.entrypoints=web
  hubzilla:
    image: miklobit/hubzilla:5.4.2
    depends_on:
      - postgres
      - nginx
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_TYPE: pgsql
      DB_NAME: hub
      DB_USER: hubzilla
      DB_PASSWORD: hubzilla
      HUBZILLA_DOMAIN: "domain.com"
      HUBZILLA_ADMIN: "admin@domain.com"
      ADDON_LIST: "bookmarker diaspora emojione gallery navbanner_options nsfw openclipatar openstreetmap pubcrawl superblock notifyadmin"
    networks:
      - hubzilla
    volumes:
      - volweb:/var/www/html
  cron:
    image: miklobit/hubzilla:5.4.2
    depends_on:
      - postgres
    command: ["crond", "-f"]
    networks:
      - hubzilla
    volumes:
      - volweb:/var/www/html
